name: Torchao nightly workflow (A100)
on:
  workflow_dispatch:
  schedule:
    - cron: '00 18 * * *' # run at 6:00 PM UTC, K8s containers will roll out at 12PM EST

jobs:
  timm:
    uses: ./.github/workflows/_linux-benchmark-cuda.yml
    with:
      userbenchmark: "torchao"
      userbenchmark-run-args: "--ci --dashboard --timm"
      workflow_run_id: ${{ github.event.workflow_run.id }}
      workflow_run_attempt: ${{ github.event.workflow_run.run_attempt }}
    secrets:
      HUGGING_FACE_HUB_TOKEN: ${{ secrets.HUGGING_FACE_HUB_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  torchbench:
    uses: ./.github/workflows/_linux-benchmark-cuda.yml
    with:
      userbenchmark: "torchao"
      userbenchmark-run-args: "--ci --dashboard --torchbench"
      workflow_run_id: ${{ github.event.workflow_run.id }}
      workflow_run_attempt: ${{ github.event.workflow_run.run_attempt }}      
    secrets:
      HUGGING_FACE_HUB_TOKEN: ${{ secrets.HUGGING_FACE_HUB_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  huggingface:
    uses: ./.github/workflows/_linux-benchmark-cuda.yml
    with:
      userbenchmark: "torchao"
      userbenchmark-run-args: "--ci --dashboard --huggingface"
      workflow_run_id: ${{ github.event.workflow_run.id }}
      workflow_run_attempt: ${{ github.event.workflow_run.run_attempt }}      
    secrets:
      HUGGING_FACE_HUB_TOKEN: ${{ secrets.HUGGING_FACE_HUB_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.event_name == 'workflow_dispatch' }}
  cancel-in-progress: true
